reflections/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts_page/<slug:slug>/', views.posts_page, name='posts_page'),
    # path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

reflections/reflections/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
]

reflections/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title
    


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name = 'posts',
        blank=True,
        null=True
    )
    ordering = ['-pub_date']

reflections/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group

def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    groups = Group.objects.all()
    context = {
        'posts': posts,
        'groups': groups,
    }
    return render(request, template, context)

def posts_page(request, slug):
    template = 'posts/posts_page.html'
    group = get_object_or_404(Group, slug=slug)
    groups = Group.objects.all()
    posts = group.posts.all()
    context = {
        'posts': posts,
        'group': group,
        'groups': groups,
    }
    return render(request, template, context)

reflections/templates/base.html
<!DOCTYPE html> 
<html lang="ru">          
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    {% block links %}
    {% endblock %}
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% comment %} {% block groups_block %}
        Контент не подвезли
      {% endblock %} {% endcomment %}
      <div class="groups_nav">
        {% for item in groups %}
          <div class="group_item">
            <a class="group_link" href="{% url 'posts:posts_page' item.slug %}">
              <p>{{ item.title }}</p>
            </a>
          </div>
        {% endfor %}
      </div>
      {% block posts_block %}
      {% endblock %}
    </main>
    {% comment %} <footer>
      {% include 'includes/footer.html' %} 
    </footer> {% endcomment %}
  </body>
</html> 

reflections/templates/includes/footer.html
<div class="footer_box"></div>

reflections/templates/includes/header.html
<div class="header_box"></div>

reflections/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock  %}


{% block groups_block %}
  <div class="groups_nav">
    {% for item in groups %}
      <div class="group_item"><p>{{ item.title }}</p></div>
    {% endfor %}
  </div>
{% endblock %}

reflections/templates/posts/posts_page.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
  <link rel="stylesheet" href="{% static 'css/posts_page.css' %}">
{% endblock  %}


{% block groups_block %}
  <div class="groups_nav">
    {% for item in groups %}
      <div class="group_item"><p>{{ item.title }}</p></div>
    {% endfor %}
  </div>
{% endblock %}

{% block posts_block %}
  <div class="posts_box">
    <div class="group_title">{{ group.title }}</div>
    {% for post in posts %}
        <div class="post_content">
          <p>{{ post.text }}</p>
        </div>
    {% endfor %}
  </div>

{% endblock %}